### ISSUE TITLE
[RFC] Supporting hooks

### ISSUE THREAD

**Issue by troch** [fanduel-oss/refract#119]
# Supporting hooks

I think the Refract React packages could include hooks for users to be able to choose between HoC and Hooks:

- A `useRefract` hook which would be similar to `withEffects` but with minor differences and limitations (to explore).
  - Observing props: not known yet if possible, needs to be explored.
  - Observing mount should be possible (with `useLayoutEffect` triggered only the first time)
  - Observing unmount would be on internal `useEffect` hook being unsubscribed
  - Pushing events and from events shouldn't have any limitation
  - Built-in effects (`toProps`, `asProps` and JSX) can't be supported, instead a new built-in effect will be introduced for the `useRefract` hook to "return" values (like `useState`).
  - No passing of context, instead user will manually pass `initialProps` and can include context (using `useContext` before).
- A `useDeclarativeEffect` hook factory which would bring a functional alternative to the `useEffect` hook in React: bringing the global effect handler technique to hooks, but without reactive streams.

### How it could look like

`useRefract` hook would possibly need to be user-land created

```js
const useRefract = createRefractHook(handler, errorHandler)
```

```js
function MyComponent() {
    const { searchValue, setSearchValue } = useRefract(component => {
        const [searchValue$, setSearchValue] = component.useEvent('search', '')

        return searchValue$.pipe(
            map(searchValue =>
                toComponent({
                    searchValue,
                    setSearchValue
                })
            )
        )
    })

    return <input value={searchValue} onChange={setSearchValue} />
}
```

**Injecting dependencies and props**

Users will be able to pass props and context (using `useContext` before `useRefract`). Two options:
- Having `useRefract()` take a second argument
  ```js
  const dependencies = { prop1, prop2, context1 }
  const {} = useRefract(dependencies => component => {}, dependencies)
  ```
- Letting users having to create aperture factories and passing arguments, or use closures. In that case the hook API would be `useRefract(component => {/*...*/})`

**toComponent effect creator**

```js
const toComponent = (data) => ({
    type: '@@refract/effect/TO_COMPONENT',
    payload: data
})
```

**Initial implementation idea**

`useRefract` would combine `useState` (used to return state and callbacks to the user component) and `useEffect` (used to pass `component` and to subscribe / unsubscribe to the returned stream).

```js
const EmptyContext = React.createContext({})

const createRefractHook = (handler, errorHandler, DependencyContext = EmptyContext) => {
    const useRefract = (apertureFactory, initialProps) => {
        const [data, setData] = useState({})

        const dependencies = useContext(DependencyContext)

        const boundHandler = handler(initialProps, dependencies)
        const bundErrorHandler = errorHandler(initialProps, dependencies)
        const aperture = apertureFactory(initialProps, dependencies)

        useEffect(
            createEffectHook(boundHandler, bundErrorHandler, aperture, setData),
            []
        )

        return data
    }

    return useRefract
}
```

`createEffectHook` would be the equivalent of `configureComponent`.

**Comment by troch** [comment]
See #123

**Comment by jtmcgrath** [comment]
Think it's an interesting approach to explore, but I'm unconvinced it's the right direction... 😬

For me, the problem space we should be aiming for is not `how to integrate Refract into the new hooks api` - instead it's `how to integrate streams into React itself using the new hooks api`. Instead of aiming to expand the library's capabilities, we should look at what the new use case demands first! 😁 

I'm also skeptical that we can really design a good hook-based api before we've explored hooks themselves thoroughly, plus (because we're used to the current Refract mental model) any approach would benefit a lot from significant input from others in the team who haven't used Refract much yet!

Regardless of approach, seriously feels to me like it should be a separate package - different api, different dependencies, different approach, different capabilities... 😛

**Comment by troch** [comment]
That's interesting you see it as something different. To me hooks are a replacement to classes, not to the logic which is expressed with them, or the patterns used with them. So from this point of view, I see the addition of a hook as giving choice to users to use their preferred container for doing things the refract way. Besides, being able to say we run RxJS in hooks could bring attention.

Hooks are a bit different however: I'm not keen on observing props because they would need to be manually passed by the user. Mounting would be possible but would make the code weird. Finally they are interesting possibilities for hooks: using refs.

There is one thing suggested above which would be belong in a separate package: the idea of making useEffect declarative, by having a separate handler for declarative effects.

**Comment by jtmcgrath** [comment]
Yeah IMO hooks are broader than that - considering the root question which is driving this, `how do we create and consume reusable code`: classes are an implementation detail of HoCs and render props; hooks aim not just to replace that implementation detail but _also_ to replace the user-facing API. If that's correct, it means this is a different pattern of use, so any API built with them should really be tailored to this new pattern.

Trying to provide close to the same API feels like it would not be tailoring it to the situation, especially when we're having to limit the functionality a lot to get it to work at all. Pretty sure it would become clear whether that feeling is right or not given some time experimenting with hooks, and there's no need to rush! ¯\\\_(ツ)_/¯

And this kind of caveat in particular does make me doubt whether the existing API is applicable: `not keen on observing props because they would need to be manually passed by the user` - for me the killer feature of Refract is `component.observe`, because it lets you treat data flowing through React as an observable.

Without that, what is left? A pattern for dispatching and responding to actions in Rx? Might there not be more expressive or less complex ways to do the same now that we're reduced to just using Rx in hooks? 🤔

**Comment by troch** [comment]
> Yeah IMO hooks are broader than that - considering the root question which is driving this, how do we create and consume reusable code: classes are an implementation detail of HoCs and render props; hooks aim not just to replace that implementation detail but also to replace the user-facing API.

We could use hooks to power `withEffects` and we would get the same level of functionality. But I don't see a compelling reason to do it, unless React deprecates classes. The aim is here is to bring Refract to hooks, not hooks to Refract: i.e. it's aimed at users, so they can have the choice to use hooks to express their Refract logic. When writing a custom hook, your only implementation option is to use hooks. But it's really not the other way round (implementing with hooks --> exposing a hook).

> If that's correct, it means this is a different pattern of use, so any API built with them should really be tailored to this new pattern

There is a distinction between how functionality is exposed (API), and how it is composed / consumed. About `how do we create and consume reusable code`: classes were the only option to do it before hooks (separating rendering from lifecycle logic), and it drove the use of HoCs (for composition). Now hooks are an alternative / replacement to classes: separating logic is achieved with custom hooks, and composition is done by invoking hooks. But it terms of what API you expose with your custom hook or HoC, I don't think it's fair to say that it has to follow a pattern: again distinction between composition and API has to be made. Consider the following:

**Composing with HoC**

```js
function Counter({ count, addOne }) {
    return <button onClick={() => addOne()}>{count}</button>
}

export default withState(
    { count: 0 },
    { plusOne: () => ({ count }) => ({ count: count + 1 }) }
)(Counter)
```

**Composing with hooks**

(Imagine a custom `useState` similar to `withState`)

```js
function Counter() {
    const { count, addOne } = useState(
        { count: 0 },
        { plusOne: () => ({ count }) => ({ count: count + 1 }) }
    )
    return <button onClick={() => addOne()}>{count}</button>
}
```

That's kind of the same, but it's composed differently, it's only one component, and `useState` doesn't need the 3rd argument of `withState`.

> Trying to provide close to the same API feels like it would not be tailoring it to the situation, especially when we're having to limit the functionality a lot to get it to work at all. Pretty sure it would become clear whether that feeling is right or not given some time experimenting with hooks, and there's no need to rush! ¯\_(ツ)_/¯

I am very much experimenting :). I have made hypothesises on whether something was possible or not, and then tried to verify them. The open PR is the 3rd implementation, and I've binned the other two. The initial implementations were incorrect for various reasons like using the wrong hooks and making wrong assumptions. Each time, I go through each stream library implementation, I don't really call that rushing.

It turns out there is not as much limitations than initially thought. I initially tried to get it working, to validate the use of effect hooks to run streams and unsubscribe when done. And then with a bit more knowledge and understanding of what is possible with hooks (given the right ones are called), I was able to refine the implementation. One thing obvious to me now: it is very much like classes and you find the same caveats, like `setState` is a noop before mounting. **The difference is on props**: they are accessed in the component scope, not in the hooks themselves.

> And this kind of caveat in particular does make me doubt whether the existing API is applicable: not keen on observing props because they would need to be manually passed by the user - for me the killer feature of Refract is component.observe, because it lets you treat data flowing through React as an observable.

`observe` is an important feature, but I wouldn't say it's the killer feature. Events gave the power to turn apertures into state containers, and `observe` is very much to observe state (external to the aperture), since props mainly come from state. I think it boils down to this: observing props is possible with hooks, but it doesn't make sense to me right now (it might change). It doesn't make sense because my initial thoughts are: if you want to observe props passed to a component, it feels like you should be outside that component, not inside.

Last iteration: everything is possible (mount & unmount implemented), `observe()` is not implemented by choice.

**Comment by troch** [comment]
A hook was added to v3.0.0 of Refract
