### ISSUE TITLE
unable to get the `useRefract` demo code to work

### ISSUE THREAD

**Issue by dfee** [fanduel-oss/refract#141]
I created a simple codesandbox trying to reproduce the code example from the docs, but i couldn't get it to work. 

[Here's the example](https://codesandbox.io/s/5v2pw38k7l)

**Comment by jtmcgrath** [comment]
Hey, looks like there are a couple of issues in your code - [here's a fixed version](https://codesandbox.io/s/pn1v8zlzm)!

**Comment by jtmcgrath** [comment]
Saw that these errors were copied over from the example code in the docs - fixed that in #142; thanks for highlighting it!
