### ISSUE TITLE
'componentWillReceiveProps' deprecation warning from WithEffects

### ISSUE THREAD

**Issue by cvs-mrussell** [fanduel-oss/refract#154]
Hi,

I've started experimenting with Refract, it looks like a great fit for some things we're trying to do. I noticed the following - using React v16.9.0, from `create-react-app`, I see the following warning in the browser console:
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: WithEffects
```

I looked at the source for `withEffects.ts`, and verified it is using the old `componentWillReceiveProps` method.

**Comment by thisRaptori** [comment]
Thanks for posting this @cvs-mrussell!

We'll be taking a look at what the long-term solution should be - if it's not much effort we'll go ahead with it, if not we'll switch to the `UNSAFE_componentWillReceiveProps` method temporarily. 🙂

**Comment by cvs-mrussell** [comment]
Hey, thanks for the quick response. Yeah, I'm not sure that it's as easy as just moving code to `componentDidReceiveProps`, but just switching to the UNSAFE method makes sense for now.
Thanks!
