### ISSUE TITLE
Is this project done for?

### ISSUE THREAD

**Issue by idfunctor** [fanduel-oss/refract#173]
Hey guys!  I was very excited when I first read about this and the concept is very enticing. I just wanna know if this project is "dead" or has plans to be actively developed any more.

**Comment by thisRaptori** [comment]
Hey! I've answered this elsewhere, but good to have an issue about this specifically so thanks for asking.

It's still in use, and any bugs or issues (and potentially feature requests from others) would be sorted out, but neither me nor @troch work with it day-to-day any more, so we don't personally need to add anything to it. I'd still 100% recommend it though, and would use it in future projects where appropriate!

**Comment by orshick** [comment]
@thisRaptori when I asked a similar question in the reactiflux discord, you quoted this answer, and also added " i find that hooks cause way more problems, but they do have the advantage of being more well-known. personally i'd prefer to use refract (using `withEffects` hoc, not the hook) than use hooks, but for a project involving other people it'd also be important to take others opinions/experience into account". 

I just wanted to follow up to ask if you can elaborate on why hooks prevented rx-js integration libraries from moving forward. Is there a general impression that even though hooks are not perfect, they solve the rxjs use-case enough that exploring alternative solutions is now a hill too steep to climb, and maybe even counter-productive given their momentum? Or is there simply an opportunity now in the react ecosystem for a hooks-aware Rx-js integration library for React?

**Comment by idfunctor** [comment]
@thisRaptori thanks a huge lot for your response!

I feel like it will get a bit too unwieldy if I "userland" my way through doing React with Rx but without Redux Observable. For this new project I feel like I can let go of Redux if I had a library like this to work with. 
I don't necessarily need "more features" from this, as I feel like apertures and handlers are exactly what I need to have Reactive code without using "useObservable" hooks everywhere.
I just didn't want to build a production app on a dependency that might never get updated with let's say some breaking changes from new Rx or React versions, etc.
Knowing that you still recommend it and would be actively helping maintain this if there's bugs really puts my mind at ease.
